# Generated by Django 5.0 on 2023-12-31 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bld',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('fname', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('type', models.CharField(max_length=4)),
                ('add', models.CharField(max_length=40)),
                ('mob', models.IntegerField()),
            ],
        ),
    ]
