# Generated by Django 5.0 on 2024-01-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='naya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ImageField(upload_to='image')),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
