# Generated by Django 5.0 on 2024-01-31 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_app', '0003_remove_naya_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='naya',
            name='img',
            field=models.ImageField(default=0, upload_to='Image'),
            preserve_default=False,
        ),
    ]
