# Generated by Django 5.0 on 2024-02-10 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood_app', '0004_naya_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bld',
        ),
    ]
